#!/bin/bash
SQL_USER='poolie'
SQL_PASSWORD='lagisbad'
SQL_HOST='mysql.server'
SQL_PORT='3306'
SQL_DATABASE_NAME='poolie$poolie'
SQL_LOG_DATE=$(date +"%F")
mysqldump --host=$SQL_HOST --port=$SQL_PORT --user=$SQL_USER --password=$SQL_PASSWORD $SQL_DATABASE_NAME > ../DbBackup-$SQL_LOG_DATE.sql